/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package test;

import dao.UserDAO;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Killer
 */
public class RecherchePanel extends javax.swing.JPanel {

    Boolean sexe=null;
    String type="Admin Forum Parent Pediatre ";
    /**
     * Creates new form RecherchePanel
     */
    public RecherchePanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        sexeBG = new javax.swing.ButtonGroup();
        dateNaissanceDP = new org.jdesktop.swingx.JXDatePicker();
        dateInscriptionDP = new org.jdesktop.swingx.JXDatePicker();
        supprimerB = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        emailTF = new javax.swing.JTextField();
        viderChampsB = new javax.swing.JButton();
        consulterB = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        pediatreCB = new javax.swing.JCheckBox();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        prenomTF = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        nomTF = new javax.swing.JTextField();
        adminCB = new javax.swing.JCheckBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        rechercheT = new javax.swing.JTable();
        jLabel9 = new javax.swing.JLabel();
        parentCB = new javax.swing.JCheckBox();
        forumCB = new javax.swing.JCheckBox();
        loginTF = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        nationnaliteTF = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        hommeRB = new javax.swing.JRadioButton();
        femmeRB = new javax.swing.JRadioButton();
        tousRB = new javax.swing.JRadioButton();
        jLabel8 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));

        dateNaissanceDP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dateNaissanceDPActionPerformed(evt);
            }
        });
        dateNaissanceDP.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                dateNaissanceDPPropertyChange(evt);
            }
        });

        dateInscriptionDP.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                dateInscriptionDPPropertyChange(evt);
            }
        });

        supprimerB.setText("Supprimer le profil");
        supprimerB.setEnabled(false);
        supprimerB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                supprimerBActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel5.setText("Date d'inscription");

        emailTF.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                emailTFKeyReleased(evt);
            }
        });

        viderChampsB.setText("Vider les champs");
        viderChampsB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viderChampsBActionPerformed(evt);
            }
        });

        consulterB.setText("Consulter le profil");
        consulterB.setEnabled(false);
        consulterB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consulterBActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel6.setText("Date de Naissance");

        pediatreCB.setBackground(new java.awt.Color(255, 255, 255));
        pediatreCB.setSelected(true);
        pediatreCB.setText("Pédiatre");
        pediatreCB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pediatreCBActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setText("Nom");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setText("E-mail");

        prenomTF.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                prenomTFKeyReleased(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setText("Prenom");

        nomTF.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                nomTFKeyReleased(evt);
            }
        });

        adminCB.setBackground(new java.awt.Color(255, 255, 255));
        adminCB.setSelected(true);
        adminCB.setText("Administrateur");
        adminCB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adminCBActionPerformed(evt);
            }
        });

        rechercheT.setModel(new RechercheTableModel(loginTF.getText(), nomTF.getText(),prenomTF.getText(),emailTF.getText(),nationnaliteTF.getText(),dateInscriptionDP.getDate(),dateNaissanceDP.getDate(),sexe,type.split(" ")));
        rechercheT.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        rechercheT.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rechercheTMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                rechercheTMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                rechercheTMouseReleased(evt);
            }
        });
        rechercheT.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                rechercheTMouseDragged(evt);
            }
        });
        rechercheT.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                rechercheTKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                rechercheTKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                rechercheTKeyTyped(evt);
            }
        });
        jScrollPane1.setViewportView(rechercheT);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel9.setText("Type");

        parentCB.setBackground(new java.awt.Color(255, 255, 255));
        parentCB.setSelected(true);
        parentCB.setText("Parent");
        parentCB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                parentCBActionPerformed(evt);
            }
        });

        forumCB.setBackground(new java.awt.Color(255, 255, 255));
        forumCB.setSelected(true);
        forumCB.setText("Administrateur forum");
        forumCB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                forumCBActionPerformed(evt);
            }
        });

        loginTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginTFActionPerformed(evt);
            }
        });
        loginTF.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                loginTFKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                loginTFKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                loginTFKeyTyped(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setText("Login");

        nationnaliteTF.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                nationnaliteTFKeyReleased(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel7.setText("Nationnalité");

        hommeRB.setBackground(new java.awt.Color(255, 255, 255));
        sexeBG.add(hommeRB);
        hommeRB.setText("Homme");
        hommeRB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hommeRBActionPerformed(evt);
            }
        });

        femmeRB.setBackground(new java.awt.Color(255, 255, 255));
        sexeBG.add(femmeRB);
        femmeRB.setText("Femme");
        femmeRB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                femmeRBActionPerformed(evt);
            }
        });

        tousRB.setBackground(new java.awt.Color(255, 255, 255));
        sexeBG.add(tousRB);
        tousRB.setSelected(true);
        tousRB.setText("Tous");
        tousRB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tousRBActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel8.setText("Sexe");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(viderChampsB)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel8)
                                .addComponent(jLabel6)
                                .addComponent(jLabel7)
                                .addComponent(jLabel5))
                            .addGap(4, 4, 4)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(pediatreCB)
                                .addComponent(parentCB)
                                .addComponent(forumCB)
                                .addComponent(adminCB)
                                .addComponent(nomTF)
                                .addComponent(prenomTF)
                                .addComponent(emailTF)
                                .addComponent(dateInscriptionDP, javax.swing.GroupLayout.DEFAULT_SIZE, 173, Short.MAX_VALUE)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(2, 2, 2)
                                    .addComponent(hommeRB)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(femmeRB)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(tousRB))
                                .addComponent(dateNaissanceDP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(nationnaliteTF)
                                .addComponent(loginTF)))
                        .addComponent(jLabel3)
                        .addComponent(jLabel2)
                        .addComponent(jLabel1)
                        .addComponent(jLabel9)
                        .addComponent(jLabel4)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 703, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(supprimerB)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(consulterB)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(adminCB))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(forumCB)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(parentCB)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pediatreCB)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(loginTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(nomTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(prenomTF, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(emailTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(hommeRB)
                            .addComponent(femmeRB)
                            .addComponent(tousRB))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(dateNaissanceDP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(dateInscriptionDP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(nationnaliteTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(consulterB)
                    .addComponent(supprimerB)
                    .addComponent(viderChampsB))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void dateNaissanceDPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dateNaissanceDPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dateNaissanceDPActionPerformed

    private void dateNaissanceDPPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_dateNaissanceDPPropertyChange
        // TODO add your handling code here:
        rechercheT.setModel(new RechercheTableModel(loginTF.getText(), nomTF.getText(),prenomTF.getText(),emailTF.getText(),nationnaliteTF.getText(),dateInscriptionDP.getDate(),dateNaissanceDP.getDate(),sexe,type.split(" ")));
    }//GEN-LAST:event_dateNaissanceDPPropertyChange

    private void dateInscriptionDPPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_dateInscriptionDPPropertyChange
        // TODO add your handling code here:
        rechercheT.setModel(new RechercheTableModel(loginTF.getText(), nomTF.getText(),prenomTF.getText(),emailTF.getText(),nationnaliteTF.getText(),dateInscriptionDP.getDate(),dateNaissanceDP.getDate(),sexe,type.split(" ")));
    }//GEN-LAST:event_dateInscriptionDPPropertyChange

    private void supprimerBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_supprimerBActionPerformed
        if(rechercheT.getSelectedRow()!=-1){
            String login= (String)rechercheT.getValueAt(rechercheT.getSelectedRow(), 0);
            if (JOptionPane.showConfirmDialog(null,"Êtes-vous sur de vouloir supprimer l'utilisateur "+login+" ?","Confirmation de suppression.",JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE )==JOptionPane.YES_OPTION) {
                new UserDAO().deleteUser(login);
                rechercheT.setModel(new RechercheTableModel(loginTF.getText(), nomTF.getText(),prenomTF.getText(),emailTF.getText(),nationnaliteTF.getText(),dateInscriptionDP.getDate(),dateNaissanceDP.getDate(),sexe,type.split(" ")));
            }
        }

    }//GEN-LAST:event_supprimerBActionPerformed

    private void emailTFKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_emailTFKeyReleased
        // TODO add your handling code here:
        rechercheT.setModel(new RechercheTableModel(loginTF.getText(), nomTF.getText(),prenomTF.getText(),emailTF.getText(),nationnaliteTF.getText(),dateInscriptionDP.getDate(),dateNaissanceDP.getDate(),sexe,type.split(" ")));
    }//GEN-LAST:event_emailTFKeyReleased

    private void viderChampsBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viderChampsBActionPerformed
        // TODO add your handling code here:
        loginTF.setText("");
        nomTF.setText("");
        prenomTF.setText("");
        dateInscriptionDP.setDate(null);
        dateNaissanceDP.setDate(null);
        emailTF.setText("");
        nationnaliteTF.setText("");
        rechercheT.setModel(new RechercheTableModel(loginTF.getText(), nomTF.getText(),prenomTF.getText(),emailTF.getText(),nationnaliteTF.getText(),dateInscriptionDP.getDate(),dateNaissanceDP.getDate(),sexe,type.split(" ")));
    }//GEN-LAST:event_viderChampsBActionPerformed

    private void consulterBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consulterBActionPerformed
        // TODO add your handling code here:
        if(rechercheT.getSelectedRow() == -1) return;
        JFrame pf;
        String typeP=(String) rechercheT.getValueAt(rechercheT.getSelectedRow(), 8);
        String loginP=(String) rechercheT.getValueAt(rechercheT.getSelectedRow(), 0);
        if("parent".equals(typeP))pf= new ParentForm(loginP);
        else if("admin".equals(typeP)) pf= new AdminForm(loginP);
        else if("forum".equals(typeP)) pf= new AdminForumForm(loginP);
        else pf=new PediatreForm(loginP);
        pf.setVisible(true);
    }//GEN-LAST:event_consulterBActionPerformed

    private void pediatreCBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pediatreCBActionPerformed
        // TODO add your handling code here:
        if(pediatreCB.isSelected()) type += "Pediatre ";
        else type = type.replace("Pediatre ", "");
        rechercheT.setModel(new RechercheTableModel(loginTF.getText(), nomTF.getText(),prenomTF.getText(),emailTF.getText(),nationnaliteTF.getText(),dateInscriptionDP.getDate(),dateNaissanceDP.getDate(),sexe,type.split(" ")));
    }//GEN-LAST:event_pediatreCBActionPerformed

    private void prenomTFKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_prenomTFKeyReleased
        // TODO add your handling code here:
        rechercheT.setModel(new RechercheTableModel(loginTF.getText(), nomTF.getText(),prenomTF.getText(),emailTF.getText(),nationnaliteTF.getText(),dateInscriptionDP.getDate(),dateNaissanceDP.getDate(),sexe,type.split(" ")));
    }//GEN-LAST:event_prenomTFKeyReleased

    private void nomTFKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nomTFKeyReleased
        // TODO add your handling code here:
        rechercheT.setModel(new RechercheTableModel(loginTF.getText(), nomTF.getText(),prenomTF.getText(),emailTF.getText(),nationnaliteTF.getText(),dateInscriptionDP.getDate(),dateNaissanceDP.getDate(),sexe,type.split(" ")));
    }//GEN-LAST:event_nomTFKeyReleased

    private void adminCBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adminCBActionPerformed
        // TODO add your handling code here:
        if(adminCB.isSelected()) type += "Admin ";
        else type = type.replace("Admin ", "");
        rechercheT.setModel(new RechercheTableModel(loginTF.getText(), nomTF.getText(),prenomTF.getText(),emailTF.getText(),nationnaliteTF.getText(),dateInscriptionDP.getDate(),dateNaissanceDP.getDate(),sexe,type.split(" ")));
    }//GEN-LAST:event_adminCBActionPerformed

    private void parentCBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_parentCBActionPerformed
        // TODO add your handling code here:
        if(parentCB.isSelected()) type += "Parent ";
        else type = type.replace("Parent ", "");
        rechercheT.setModel(new RechercheTableModel(loginTF.getText(), nomTF.getText(),prenomTF.getText(),emailTF.getText(),nationnaliteTF.getText(),dateInscriptionDP.getDate(),dateNaissanceDP.getDate(),sexe,type.split(" ")));
    }//GEN-LAST:event_parentCBActionPerformed

    private void forumCBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_forumCBActionPerformed
        // TODO add your handling code here:
        if(forumCB.isSelected()) type += "Forum ";
        else type = type.replace("Forum ", "");
        rechercheT.setModel(new RechercheTableModel(loginTF.getText(), nomTF.getText(),prenomTF.getText(),emailTF.getText(),nationnaliteTF.getText(),dateInscriptionDP.getDate(),dateNaissanceDP.getDate(),sexe,type.split(" ")));
    }//GEN-LAST:event_forumCBActionPerformed

    private void loginTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_loginTFActionPerformed

    private void loginTFKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_loginTFKeyPressed
        // TODO add your handling code here:

    }//GEN-LAST:event_loginTFKeyPressed

    private void loginTFKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_loginTFKeyReleased
        // TODO add your handling code here:
        rechercheT.setModel(new RechercheTableModel(loginTF.getText(), nomTF.getText(),prenomTF.getText(),emailTF.getText(),nationnaliteTF.getText(),dateInscriptionDP.getDate(),dateNaissanceDP.getDate(),sexe,type.split(" ")));
    }//GEN-LAST:event_loginTFKeyReleased

    private void loginTFKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_loginTFKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_loginTFKeyTyped

    private void nationnaliteTFKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nationnaliteTFKeyReleased
        // TODO add your handling code here:
        rechercheT.setModel(new RechercheTableModel(loginTF.getText(), nomTF.getText(),prenomTF.getText(),emailTF.getText(),nationnaliteTF.getText(),dateInscriptionDP.getDate(),dateNaissanceDP.getDate(),sexe,type.split(" ")));
    }//GEN-LAST:event_nationnaliteTFKeyReleased

    private void hommeRBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hommeRBActionPerformed
        // TODO add your handling code here:
        sexe= new Boolean(true);
        rechercheT.setModel(new RechercheTableModel(loginTF.getText(), nomTF.getText(),prenomTF.getText(),emailTF.getText(),nationnaliteTF.getText(),dateInscriptionDP.getDate(),dateNaissanceDP.getDate(),sexe,type.split(" ")));
    }//GEN-LAST:event_hommeRBActionPerformed

    private void femmeRBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_femmeRBActionPerformed
        // TODO add your handling code here:
        sexe= new Boolean(false);
        rechercheT.setModel(new RechercheTableModel(loginTF.getText(), nomTF.getText(),prenomTF.getText(),emailTF.getText(),nationnaliteTF.getText(),dateInscriptionDP.getDate(),dateNaissanceDP.getDate(),sexe,type.split(" ")));
    }//GEN-LAST:event_femmeRBActionPerformed

    private void tousRBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tousRBActionPerformed
        // TODO add your handling code here:
        sexe= null;
        rechercheT.setModel(new RechercheTableModel(loginTF.getText(), nomTF.getText(),prenomTF.getText(),emailTF.getText(),nationnaliteTF.getText(),dateInscriptionDP.getDate(),dateNaissanceDP.getDate(),sexe,type.split(" ")));
    }//GEN-LAST:event_tousRBActionPerformed

    private void rechercheTKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_rechercheTKeyPressed
        // TODO add your handling code here:
        if(rechercheT.getSelectedRow() >= 0){
            consulterB.setEnabled(true);
            supprimerB.setEnabled(true);
        }
        else{
            consulterB.setEnabled(false);
            supprimerB.setEnabled(false);
        }
    }//GEN-LAST:event_rechercheTKeyPressed

    private void rechercheTKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_rechercheTKeyReleased
        // TODO add your handling code here:
        if(rechercheT.getSelectedRow() >= 0){
            consulterB.setEnabled(true);
            supprimerB.setEnabled(true);
        }
        else{
            consulterB.setEnabled(false);
            supprimerB.setEnabled(false);
        }
    }//GEN-LAST:event_rechercheTKeyReleased

    private void rechercheTKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_rechercheTKeyTyped
        // TODO add your handling code here:
        if(rechercheT.getSelectedRow() >= 0){
            consulterB.setEnabled(true);
            supprimerB.setEnabled(true);
        }
        else{
            consulterB.setEnabled(false);
            supprimerB.setEnabled(false);
        }
    }//GEN-LAST:event_rechercheTKeyTyped

    private void rechercheTMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rechercheTMouseClicked
        // TODO add your handling code here:
        if(rechercheT.getSelectedRow() >= 0){
            consulterB.setEnabled(true);
            supprimerB.setEnabled(true);
        }
        else{
            consulterB.setEnabled(false);
            supprimerB.setEnabled(false);
        }
    }//GEN-LAST:event_rechercheTMouseClicked

    private void rechercheTMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rechercheTMouseDragged
        // TODO add your handling code here:
        if(rechercheT.getSelectedRow() >= 0){
            consulterB.setEnabled(true);
            supprimerB.setEnabled(true);
        }
        else{
            consulterB.setEnabled(false);
            supprimerB.setEnabled(false);
        }
    }//GEN-LAST:event_rechercheTMouseDragged

    private void rechercheTMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rechercheTMousePressed
        // TODO add your handling code here:
        if(rechercheT.getSelectedRow() >= 0){
            consulterB.setEnabled(true);
            supprimerB.setEnabled(true);
        }
        else{
            consulterB.setEnabled(false);
            supprimerB.setEnabled(false);
        }
    }//GEN-LAST:event_rechercheTMousePressed

    private void rechercheTMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rechercheTMouseReleased
        // TODO add your handling code here:
        if(rechercheT.getSelectedRow() >= 0){
            consulterB.setEnabled(true);
            supprimerB.setEnabled(true);
        }
        else{
            consulterB.setEnabled(false);
            supprimerB.setEnabled(false);
        }
    }//GEN-LAST:event_rechercheTMouseReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox adminCB;
    private javax.swing.JButton consulterB;
    private org.jdesktop.swingx.JXDatePicker dateInscriptionDP;
    private org.jdesktop.swingx.JXDatePicker dateNaissanceDP;
    private javax.swing.JTextField emailTF;
    private javax.swing.JRadioButton femmeRB;
    private javax.swing.JCheckBox forumCB;
    private javax.swing.JRadioButton hommeRB;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField loginTF;
    private javax.swing.JTextField nationnaliteTF;
    private javax.swing.JTextField nomTF;
    private javax.swing.JCheckBox parentCB;
    private javax.swing.JCheckBox pediatreCB;
    private javax.swing.JTextField prenomTF;
    private javax.swing.JTable rechercheT;
    private javax.swing.ButtonGroup sexeBG;
    private javax.swing.JButton supprimerB;
    private javax.swing.JRadioButton tousRB;
    private javax.swing.JButton viderChampsB;
    // End of variables declaration//GEN-END:variables
}
