/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package test;

import java.awt.Color;
import java.awt.FontMetrics;
import javax.swing.JComponent;
import javax.swing.SwingUtilities;
import javax.swing.UIManager;
import javax.swing.event.ChangeEvent;
import javax.swing.event.ChangeListener;
import javax.swing.plaf.basic.BasicTabbedPaneUI;

/**
 *
 * @author Killer
 */
public class TestFrame extends javax.swing.JFrame {

    /**
     * Creates new form TestFrame
     */
    public TestFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new GradientPanel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        mainTabbedPane = new javax.swing.JTabbedPane();
        mainTabbedPane.setUI(new BasicTabbedPaneUI() {
            @Override
            protected int calculateTabHeight(int tabPlacement, int tabIndex, int fontHeight) {
                return 30;
            }
        });
        mainTabbedPane.addChangeListener(new ChangeListener() {
            public void stateChanged(ChangeEvent e) {
                for(int i=0; i<mainTabbedPane.getTabCount(); i++){
                    if(i == mainTabbedPane.getSelectedIndex()){
                        mainTabbedPane.setBackgroundAt(i, Color.WHITE);
                        mainTabbedPane.setForegroundAt(i, Color.DARK_GRAY);
                    }
                    else{
                        mainTabbedPane.setBackgroundAt(i, Color.DARK_GRAY);
                        mainTabbedPane.setForegroundAt(i, Color.WHITE);
                    }
                }
            }
        });
        gestionUsersContainer = new javax.swing.JPanel();
        gestionUsersContainer = new ContainerGradientPanel();
        gestionUserPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        ajoutPediatresContainer = new javax.swing.JPanel();
        ajoutPediatresContainer = new ContainerGradientPanel();
        jLabel2 = new javax.swing.JLabel();
        ajoutPediatresPanel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jSeparator1.setBackground(new java.awt.Color(127, 138, 150));

        jSeparator4.setBackground(new java.awt.Color(145, 147, 148));
        jSeparator4.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jSeparator2.setBackground(new java.awt.Color(127, 138, 150));
        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jSeparator3.setBackground(new java.awt.Color(62, 105, 156));

        mainTabbedPane.setBackground(new java.awt.Color(255, 255, 255));
        mainTabbedPane.setTabPlacement(javax.swing.JTabbedPane.LEFT);
        mainTabbedPane.setFocusable(false);
        mainTabbedPane.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N

        gestionUsersContainer.setBackground(new java.awt.Color(255, 255, 255));

        gestionUserPanel.setBackground(new java.awt.Color(255, 255, 255));
        gestionUserPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        javax.swing.GroupLayout gestionUserPanelLayout = new javax.swing.GroupLayout(gestionUserPanel);
        gestionUserPanel.setLayout(gestionUserPanelLayout);
        gestionUserPanelLayout.setHorizontalGroup(
            gestionUserPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        gestionUserPanelLayout.setVerticalGroup(
            gestionUserPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 299, Short.MAX_VALUE)
        );

        gestionUserPanel = new RecherchePanel();

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(39, 58, 138));
        jLabel1.setText("Gestion des utilisateurs");

        javax.swing.GroupLayout gestionUsersContainerLayout = new javax.swing.GroupLayout(gestionUsersContainer);
        gestionUsersContainer.setLayout(gestionUsersContainerLayout);
        gestionUsersContainerLayout.setHorizontalGroup(
            gestionUsersContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(gestionUsersContainerLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(gestionUsersContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(gestionUsersContainerLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 476, Short.MAX_VALUE))
                    .addComponent(gestionUserPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        gestionUsersContainerLayout.setVerticalGroup(
            gestionUsersContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, gestionUsersContainerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(gestionUserPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        mainTabbedPane.addTab("Gestion des utilisateurs", gestionUsersContainer);

        ajoutPediatresContainer.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(39, 58, 138));
        jLabel2.setText("Traitements des demandes d'ajouts des nouveaux pédiatres");

        ajoutPediatresPanel.setBackground(new java.awt.Color(255, 255, 255));
        ajoutPediatresPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        javax.swing.GroupLayout ajoutPediatresPanelLayout = new javax.swing.GroupLayout(ajoutPediatresPanel);
        ajoutPediatresPanel.setLayout(ajoutPediatresPanelLayout);
        ajoutPediatresPanelLayout.setHorizontalGroup(
            ajoutPediatresPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        ajoutPediatresPanelLayout.setVerticalGroup(
            ajoutPediatresPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 299, Short.MAX_VALUE)
        );

        ajoutPediatresPanel = new AjoutPediatres();
        ajoutPediatresPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        javax.swing.GroupLayout ajoutPediatresContainerLayout = new javax.swing.GroupLayout(ajoutPediatresContainer);
        ajoutPediatresContainer.setLayout(ajoutPediatresContainerLayout);
        ajoutPediatresContainerLayout.setHorizontalGroup(
            ajoutPediatresContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ajoutPediatresContainerLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ajoutPediatresContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ajoutPediatresPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(ajoutPediatresContainerLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(0, 246, Short.MAX_VALUE)))
                .addContainerGap())
        );
        ajoutPediatresContainerLayout.setVerticalGroup(
            ajoutPediatresContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ajoutPediatresContainerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ajoutPediatresPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        mainTabbedPane.addTab("Demandes d'ajouts de pédiatres", ajoutPediatresContainer);

        javax.swing.GroupLayout mainPanelLayout = new javax.swing.GroupLayout(mainPanel);
        mainPanel.setLayout(mainPanelLayout);
        mainPanelLayout.setHorizontalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator4)
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator2)
                            .addComponent(mainTabbedPane))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        mainPanelLayout.setVerticalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator3)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(mainTabbedPane))
                    .addComponent(jSeparator1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        mainTabbedPane.getAccessibleContext().setAccessibleName("tab");
        for(int i=0; i<mainTabbedPane.getTabCount(); i++)
        if(i == mainTabbedPane.getSelectedIndex()){
            mainTabbedPane.setBackgroundAt(i, Color.WHITE);
            mainTabbedPane.setForegroundAt(i, Color.DARK_GRAY);
        }
        else{
            mainTabbedPane.setBackgroundAt(i, Color.DARK_GRAY);
            mainTabbedPane.setForegroundAt(i, Color.WHITE);
        }

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        String system_lf = UIManager.getSystemLookAndFeelClassName().toLowerCase();
        if(system_lf.contains("metal")){
            try {
                UIManager.setLookAndFeel("com.sun.java.swing.plaf.nimbus.NimbusLookAndFeel");
                }catch (Exception e) {}
        }else{
            try {
                UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
            }catch (Exception e) {}
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TestFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel ajoutPediatresContainer;
    private javax.swing.JPanel ajoutPediatresPanel;
    private javax.swing.JPanel gestionUserPanel;
    private javax.swing.JPanel gestionUsersContainer;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JTabbedPane mainTabbedPane;
    // End of variables declaration//GEN-END:variables
}
